/**
 * 3D model generator
 * Ported from JLC2KiCadLib Python model3d.py
 */

const WRL_HEADER = `#VRML V2.0 utf8
# Generated by JLC2KiCad_lib TypeScript port
`;

interface Material {
  ambientColor: string[];
  diffuseColor: string[];
  specularColor: string[];
  transparency: string;
}

export function convertObjToWrl(objText: string): string {
  let wrlContent = WRL_HEADER;

  // Parse materials
  const materials: Record<string, Material> = {};
  // Split by "newmtl" and parse each block
  const mtlMatches: string[] = [];
  const mtlSections = objText.split("newmtl ");
  for (let i = 1; i < mtlSections.length; i++) {
    mtlMatches.push("newmtl " + mtlSections[i]);
  }
  for (const match of mtlMatches) {
    let materialId = "";
    const mat: Partial<Material> = {};
    for (const line of match.split("\n")) {
      if (line.startsWith("newmtl")) materialId = line.split(" ")[1];
      else if (line.startsWith("Ka")) mat.ambientColor = line.split(" ").slice(1);
      else if (line.startsWith("Kd")) mat.diffuseColor = line.split(" ").slice(1);
      else if (line.startsWith("Ks")) mat.specularColor = line.split(" ").slice(1);
      else if (line.startsWith("d ")) mat.transparency = line.split(" ")[1];
    }
    if (materialId) {
      materials[materialId] = {
        ambientColor: mat.ambientColor ?? ["0.2", "0.2", "0.2"],
        diffuseColor: mat.diffuseColor ?? ["0.8", "0.8", "0.8"],
        specularColor: mat.specularColor ?? ["0.0", "0.0", "0.0"],
        transparency: mat.transparency ?? "0",
      };
    }
  }

  // Parse vertices
  const vertexPattern = /^v (.*?)$/gm;
  const vertices: string[] = [];
  let vMatch: RegExpExecArray | null;
  while ((vMatch = vertexPattern.exec(objText)) !== null) {
    const coords = vMatch[1].split(" ").map((c) => String(Math.round((parseFloat(c) / 2.54) * 10000) / 10000));
    vertices.push(coords.join(" "));
  }

  // Parse shapes
  const shapes = objText.split("usemtl").slice(1);
  for (const shape of shapes) {
    const lines = shape.split("\n");
    const materialName = lines[0].replace(" ", "");
    const material = materials[materialName];
    if (!material) continue;

    let indexCounter = 0;
    const linkDict: Record<number, number> = {};
    const coordIndex: string[] = [];
    const points: string[] = [];

    for (const line of lines.slice(1)) {
      if (!line.trim()) continue;
      const parts = line.trim().split(" ");
      if (parts[0] !== "f") continue;
      const face = parts.slice(1).map((p) => parseInt(p.replace("//", "").split("/")[0]));
      const faceIndex: string[] = [];
      for (const idx of face) {
        if (!(idx in linkDict)) {
          linkDict[idx] = indexCounter;
          faceIndex.push(String(indexCounter));
          points.push(vertices[idx - 1] ?? "0 0 0");
          indexCounter++;
        } else {
          faceIndex.push(String(linkDict[idx]));
        }
      }
      faceIndex.push("-1");
      coordIndex.push(faceIndex.join(",") + ",");
    }

    if (points.length === 0) continue;

    wrlContent += `
Shape{
\tappearance Appearance {
\t\tmaterial  Material \t{ 
\t\t\tdiffuseColor ${material.diffuseColor.join(" ")} 
\t\t\tspecularColor ${material.specularColor.join(" ")}
\t\t\tambientIntensity 0.2
\t\t\ttransparency ${material.transparency}
\t\t\tshininess 0.5
\t\t}
\t}
\tgeometry IndexedFaceSet {
\t\tccw TRUE 
\t\tsolid FALSE
\t\tcoord DEF co Coordinate {
\t\t\tpoint [
\t\t\t\t${points.join(", ")}
\t\t\t]
\t\t}
\t\tcoordIndex [
\t\t\t${coordIndex.join("")}
\t\t]
\t}
}`;
  }

  return wrlContent;
}
